---
- hosts: app
  vars_files:
    - vars.yml

  tasks:
    - name: Install yum packages
      yum: name={{item}} state=latest
      with_items:
        - git
        - vim
        - nodejs
        - npm

    - name: install n (node version installer/switcher)
      npm: name=n state=present global=yes

    - name: install the latest stable version of node
      shell: n stable

    - name: Create web user
      user: name=web

    - name: Create project folder
      file: path=/var/www group=web owner=web mode=755 state=directory

    - name: Add systemd conf
      template: src=templates/systemd.service.j2 dest=/etc/systemd/system/{{project_name}}.service
      notify:
        - enable {{project_name}}

  handlers:
    - name: enable {{project_name}}
      shell: systemctl enable {{project_name}}
